//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskk4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SIZE { get; set; }
        public string PRICE { get; set; }
        public string BRAND { get; set; }
    }
}
